// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using MySql.Data.EntityFrameworkCore.Storage.Internal;
using StreamerSite.API.Data;
using System;

namespace StreamerSite.API.Migrations
{
    [DbContext(typeof(StreamersContext))]
    partial class StreamersContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026");

            modelBuilder.Entity("StreamerSite.API.Models.UserDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id");

                    b.Property<bool>("Admin");

                    b.Property<int>("FollowerCount")
                        .HasColumnName("FollowerCount");

                    b.Property<int>("PageViewCount")
                        .HasColumnName("PageViewCount");

                    b.Property<string>("Password")
                        .HasColumnName("Password")
                        .HasColumnType("TEXT")
                        .HasMaxLength(14);

                    b.Property<int>("SubscriberCount")
                        .HasColumnName("SubcriberCount");

                    b.Property<string>("Username")
                        .HasColumnName("Username")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("StreamerSite.API.Models.Video", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id");

                    b.Property<string>("Path")
                        .HasColumnName("Path");

                    b.Property<int?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Video");
                });

            modelBuilder.Entity("StreamerSite.API.Models.Video", b =>
                {
                    b.HasOne("StreamerSite.API.Models.UserDetail", "User")
                        .WithMany("Videos")
                        .HasForeignKey("UserId");
                });
#pragma warning restore 612, 618
        }
    }
}
